version: '3.7'

services:
  app:
    container_name: docker-rails-app
    stdin_open: true
    tty: true
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file: ./.env
    volumes:
      - ./:/app
      - sockets:/app/tmp/sockets
    command: bundle exec puma -C config/puma.rb
  db:
    image: mysql:8.0.23
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 4306:3306
    volumes:
      - mysql-db:/var/lib/mysql
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - sockets:/app/tmp/sockets
    depends_on:
      - app
volumes:
  mysql-db:
  sockets:
